apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  namespace: demo
  labels:
    app: zookeeper
spec:
  clusterIP: None
  ports:
    - name: server
      port: 2888
    - name: election
      port: 3888
  selector:
    app: zookeeper-app
  type: ClusterIP