apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  labels:
    app: zookeeper
spec:
  clusterIP: None
  ports:
    - name: server
      port: 2888
    - name: election
      port: 3888
  selector:
    app: zookeeper-app
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  labels:
    app: zookeeper
spec:
  ports:
    - name: client
      port: 2181
  selector:
    app: zookeeper-app
  type: ClusterIP